services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "8081:8080"
    volumes:
      - workspaces:/home/coder/workspaces
      - zeus-data:/home/coder/.zeus
    environment:
      - NODE_ENV=production
      - PORT=3000
      - PASSWORD=savvydev
    entrypoint: [ "/entrypoint.sh" ]
    restart: unless-stopped

volumes:
  workspaces:
  zeus-data:
