services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "8081:8080"
    volumes:
      - /mnt/d/docker/zeus/workspaces:/home/coder/workspaces
      - /mnt/d/docker/zeus/zeus-data:/home/coder/.zeus
    environment:
      - NODE_ENV=production
      - PORT=3000
      - PASSWORD=savvydev
      - HOST_AGENT_URL=http://host.docker.internal:3001
    entrypoint: [ "/entrypoint.sh" ]
    restart: unless-stopped

volumes:
  workspaces:
  zeus-data:
